### ISSUE TITLE
Compiling issue: libgmock.so

### ISSUE THREAD

**Issue by ewissel** [schmeing/ReSeq#5] opened 2020-08-20 19:07 UTC
I'm trying to compile ReSeq and am unable to get past `cmake ..` and `make install`.  When I run ` cmake -DCMAKE_INSTALL_PREFIX=/home/ewissel/amr-benchmarking/ReSeq/build/ .. `

I get the following output: 

```
>-- Boost version: 1.67.0
> -- Found the following Boost libraries:
> --   filesystem
> --   math_c99
> --   math_c99f
> --   math_c99l
> --   math_tr1
> --   math_tr1f
> --   math_tr1l
> --   program_options
> --   serialization
> --   system
> -- NLopt version 2.6.1
> -- Found Seqan: /home/ewissel/amr-benchmarking/ReSeq/seqan/include (found version "2.4.0")
> /usr/share/cmake-3.13/Modules/UseSWIG.cmake
> CMake Deprecation Warning at /usr/share/cmake-3.13/Modules/UseSWIG.cmake:524 (message):
>   SWIG_ADD_MODULE is deprecated.  Use SWIG_ADD_LIBRARY instead.
> Call Stack (most recent call first):
>   python/CMakeLists.txt:28 (SWIG_ADD_MODULE)
> 
> 
> CMake Warning (dev) at /usr/share/cmake-3.13/Modules/UseSWIG.cmake:564 (message):
>   Policy CMP0078 is not set.  Run "cmake --help-policy CMP0078" for policy
>   details.  Use the cmake_policy command to set the policy and suppress this
>   warning.
> Call Stack (most recent call first):
>   /usr/share/cmake-3.13/Modules/UseSWIG.cmake:525 (swig_add_library)
>   python/CMakeLists.txt:28 (SWIG_ADD_MODULE)
> This warning is for project developers.  Use -Wno-dev to suppress it.
> 
> -- Configuring done
> -- Generating done
> -- Build files have been written to: /home/ewissel/amr-benchmarking/ReSeq/build
```

When I run `make install`, I get the following output:

```
>make install
> [  2%] Built target gtest
> [  4%] Built target gmock
> [  5%] Linking CXX shared library ../../lib/libgmock_main.so
> [  6%] Built target gmock_main
> [  8%] Built target gtest_main
> [ 56%] Built target nlopt
> [ 60%] Built target skewer_matrix
> [ 72%] Built target DataStats
> [ 74%] Built target DataStatsInterface
> [ 95%] Built target reseq
> [ 96%] Built target swigtrick
> [ 97%] Built target DataStats_swig_compilation
> [100%] Built target _DataStats
> Install the project...
> -- Install configuration: "RelWithDebInfo"
> -- Up-to-date: /home/ewissel/amr-benchmarking/ReSeq/build/include
> -- Up-to-date: /home/ewissel/amr-benchmarking/ReSeq/build/include/gmock
> -- Up-to-date: /home/ewissel/amr-benchmarking/ReSeq/build/include/gmock/gmock-more-actions.h
> -- Up-to-date: /home/ewissel/amr-benchmarking/ReSeq/build/include/gmock/gmock-actions.h
> -- Up-to-date: /home/ewissel/amr-benchmarking/ReSeq/build/include/gmock/gmock-generated-actions.h.pump
> -- Up-to-date: /home/ewissel/amr-benchmarking/ReSeq/build/include/gmock/gmock-spec-builders.h
> -- Up-to-date: /home/ewissel/amr-benchmarking/ReSeq/build/include/gmock/gmock-more-matchers.h
> -- Up-to-date: /home/ewissel/amr-benchmarking/ReSeq/build/include/gmock/gmock-generated-matchers.h
> -- Up-to-date: /home/ewissel/amr-benchmarking/ReSeq/build/include/gmock/gmock-generated-function-mockers.h.pump
> -- Up-to-date: /home/ewissel/amr-benchmarking/ReSeq/build/include/gmock/gmock-cardinalities.h
> -- Up-to-date: /home/ewissel/amr-benchmarking/ReSeq/build/include/gmock/gmock-generated-actions.h
> -- Up-to-date: /home/ewissel/amr-benchmarking/ReSeq/build/include/gmock/gmock-generated-matchers.h.pump
> -- Up-to-date: /home/ewissel/amr-benchmarking/ReSeq/build/include/gmock/gmock.h
> -- Up-to-date: /home/ewissel/amr-benchmarking/ReSeq/build/include/gmock/internal
> -- Up-to-date: /home/ewissel/amr-benchmarking/ReSeq/build/include/gmock/internal/gmock-port.h
> -- Up-to-date: /home/ewissel/amr-benchmarking/ReSeq/build/include/gmock/internal/gmock-pp.h
> -- Up-to-date: /home/ewissel/amr-benchmarking/ReSeq/build/include/gmock/internal/gmock-internal-utils.h
> -- Up-to-date: /home/ewissel/amr-benchmarking/ReSeq/build/include/gmock/internal/custom
> -- Up-to-date: /home/ewissel/amr-benchmarking/ReSeq/build/include/gmock/internal/custom/gmock-generated-actions.h.pump
> -- Up-to-date: /home/ewissel/amr-benchmarking/ReSeq/build/include/gmock/internal/custom/README.md
> -- Up-to-date: /home/ewissel/amr-benchmarking/ReSeq/build/include/gmock/internal/custom/gmock-port.h
> -- Up-to-date: /home/ewissel/amr-benchmarking/ReSeq/build/include/gmock/internal/custom/gmock-generated-actions.h
> -- Up-to-date: /home/ewissel/amr-benchmarking/ReSeq/build/include/gmock/internal/custom/gmock-matchers.h
> -- Up-to-date: /home/ewissel/amr-benchmarking/ReSeq/build/include/gmock/gmock-nice-strict.h
> -- Up-to-date: /home/ewissel/amr-benchmarking/ReSeq/build/include/gmock/gmock-generated-function-mockers.h
> -- Up-to-date: /home/ewissel/amr-benchmarking/ReSeq/build/include/gmock/gmock-matchers.h
> -- Up-to-date: /home/ewissel/amr-benchmarking/ReSeq/build/include/gmock/gmock-function-mocker.h
> CMake Error at googletest/googlemock/cmake_install.cmake:51 (file):
>   file INSTALL cannot find
>   "/home/ewissel/amr-benchmarking/ReSeq/build/lib/libgmock.so".
> Call Stack (most recent call first):
>   googletest/cmake_install.cmake:42 (include)
>   cmake_install.cmake:42 (include)
>
> make: *** [Makefile:108: install] Error 1

```

I believe that the error is arising because `INSTALL` is expecting a file called `libgmock.so`, but the actual file created is called `libgmock_main.so `. I tried to copy the file (`cp libgmock_main.so  libgmock.so `), but when I run `make install`, it overrides the `lib/` directory and deletes the copied but properly named file. As a result, the package is not executable.

**Comment by schmeing** [comment] 2020-08-21 07:22
Did you update from an older version? If so please remove everything in the build folder and start again with `cmake -DCMAKE_INSTALL_PREFIX=/where/you/want/to/install/ReSeq/ ..`.
In the current version of ReSeq googletest shouldn't produce shared libraries. The `build/lib` folder should only contain the following files:
`libDataStats.a  libDataStatsInterface.a  libgmock.a  libgmock_main.a  libgtest.a  libgtest_main.a  libskewer_matrix.a`

You can also try to run `/home/ewissel/amr-benchmarking/ReSeq/build/bin/reseq test`, because the `make install` is not necessary to run the program. It only copies the important files towards the location of your choice.

**Comment by schmeing** [comment] 2020-08-29 17:03
Since the googletest libraries are linked statically they are not needed in the installation. Therefore, I removed them from the installation all together in the latest commits to the devel branch. This should fix it. Thus, I'll close the issue. In case this problem still appears, please reopen with detailed information on system, compiler, etc. , so that I can try to reproduce the issue.

**Closed by schmeing** 2020-08-29 17:03 UTC
