### ISSUE TITLE
Simulating fewer reads than desired

### ISSUE THREAD

**Issue by cilliannolan** [schmeing/ReSeq#7] opened 2020-12-21 14:45 UTC
Hi there,
I have run into an issue where ReSeq simulates fewer reads than the desired number, input with `--numReads`.

With following command:

`reseq illuminaPE --statsIn NA12878.sorted.bam.reseq --ipfIterations 0 -j 1 --refBias file --refBiasFile refbias_test.txt -r num_reads_test.fa --numReads 100000 -1 reads_R1.fastq.gz -2 reads_R2.fastq.gz > stdout 2> stderr`

Returns about 26000 reads, and is reported in the stderr like so: 
"
...
21-12-20 14:11:26: info:  Read in 26 biases from 26 biases in file refbias_test.txt
21-12-20 14:11:26: info:  Aiming for 100000 read pairs, which corresponds to an approximated read depth of 911.9x
21-12-20 14:11:26: info:  Preparing for simulation
21-12-20 14:11:27: info:  Starting read generation
21-12-20 14:11:30: info:  Generated 25900 read pairs (26%).
21-12-20 14:11:30: info:  Simulation finished succesfully
" 

I am wondering if you know why I am seeing this behaviour, and if it is possible to always produce the desired number of reads?

Files used in the above command you can access here: https://www.dropbox.com/s/arhgisfl0nx25j2/example.zip?dl=0

Thank you very much,
Cillian

**Comment by schmeing** [comment] 2020-12-23 13:27
Thank you for the awesome reporting. I could immediately reproduce the issue and it is most certainly a bug. Small fluctuations are normal and cannot be prevented, because reads are drawn independently. However, this is definitely not the issue here. I am working on finding the root cause, but most likely will not finish before the break. I will continue with it the first thing next year.

Thanks,
Stephan

**Comment by schmeing** [comment] 2021-01-04 11:45
This issue highlighted multiple bugs. I pushed the fixes to the debug branch. Thanks again for this report.
As I said before the number of read pairs is still not exact due to the random nature of the drawing process.
Running it 5 times I get:
```
Generated 99943 read pairs (100%).
Generated 100096 read pairs (100%).
Generated 99641 read pairs (100%).
Generated 100213 read pairs (100%).
Generated 100263 read pairs (100%).
```
This can not be prevented, but the more reads you simulate the lower is the fluctuation relative to the amount. If you need an exact amount I suggest simulating slightly more and randomly discarding the excess reads.

**Comment by cilliannolan** [comment] 2021-01-07 18:58
Thank you very much for the quick fix and all your help!

**Closed** 2021-01-07 18:58 UTC
